apiVersion: v1
kind: Pod
metadata:
  name: sidecar-example
spec:
  containers:
  - name: main-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: sidecar-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do date > /var/log/index.html; sleep 10; done"]
    volumeMounts:
    - name: shared-data
      mountPath: /var/log
  volumes:
  - name: shared-data
    emptyDir: {}

