apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: demo
spec:
  containers:
  - name: debug
    image: mohanacr89.azurecr.io/debug

