## In this example, container will be up, But nginx wont be available for few seconds.
apiVersion: v1
kind: Pod
metadata:
  name: probe-delay-nginx
spec:
  containers:
  - name: nginx
    image: rkalluru/delay-nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-cli
spec:
  containers:
  - name: redhat
    image: rkalluru/learnk8s:rhel9-bare

