# kubectl label nodes aks-pool1-27418639-vmss000001 apptype=demo
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-on-labeled-node
spec:
  containers:
  - name: redhat
    image: rkalluru/learnk8s:rhel9-bare
  nodeSelector:
    apptype: demo

