---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-labels
  labels:
    project: frontend
spec:
  containers:
  - name: nginx
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: with-pod-affinity
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: project
            operator: In
            values:
            - frontend
        topologyKey: topology.kubernetes.io/zone
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
            - key: project
              operator: In
              values:
              - frontend
          topologyKey: topology.kubernetes.io/zone
  containers:
  - name: nginx
    image: nginx


